# Form implementation generated from reading ui file '.\screens\dialogCrearCuenta.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogCrearCuenta(object):
    def setupUi(self, dialogCrearCuenta):
        dialogCrearCuenta.setObjectName("dialogCrearCuenta")
        dialogCrearCuenta.resize(400, 300)
        dialogCrearCuenta.setStyleSheet("dialogCrearCuenta {\n"
"    background-color: #1e1e1e;\n"
"}")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialogCrearCuenta)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lblCrearCuenta = QtWidgets.QLabel(parent=dialogCrearCuenta)
        self.lblCrearCuenta.setGeometry(QtCore.QRect(90, 60, 241, 16))
        self.lblCrearCuenta.setObjectName("lblCrearCuenta")
        self.comboxMoneda = QtWidgets.QComboBox(parent=dialogCrearCuenta)
        self.comboxMoneda.setGeometry(QtCore.QRect(150, 110, 111, 31))
        self.comboxMoneda.setStyleSheet("                                    QComboBox {\n"
"                                        background-color: #252526;\n"
"                                        border: 1px solid #3c3c3c;\n"
"                                        border-radius: 6px;\n"
"                                        padding: 2px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 14px;\n"
"                                    }")
        self.comboxMoneda.setObjectName("comboxMoneda")

        self.retranslateUi(dialogCrearCuenta)
        self.buttonBox.accepted.connect(dialogCrearCuenta.accept) # type: ignore
        self.buttonBox.rejected.connect(dialogCrearCuenta.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialogCrearCuenta)

    def retranslateUi(self, dialogCrearCuenta):
        _translate = QtCore.QCoreApplication.translate
        dialogCrearCuenta.setWindowTitle(_translate("dialogCrearCuenta", "Dialog"))
        self.lblCrearCuenta.setText(_translate("dialogCrearCuenta", "¿De que moneda querés que sea la cuenta?"))
