# Form implementation generated from reading ui file '.\screens\dialogIngresarARS.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogIngresarARS(object):
    def setupUi(self, dialogIngresarARS):
        dialogIngresarARS.setObjectName("dialogIngresarARS")
        dialogIngresarARS.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialogIngresarARS)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lblIngresarARS = QtWidgets.QLabel(parent=dialogIngresarARS)
        self.lblIngresarARS.setGeometry(QtCore.QRect(90, 60, 241, 16))
        self.lblIngresarARS.setObjectName("lblIngresarARS")
        self.lineditARS = QtWidgets.QLineEdit(parent=dialogIngresarARS)
        self.lineditARS.setGeometry(QtCore.QRect(150, 130, 111, 31))
        self.lineditARS.setStyleSheet("                                    QLineEdit {\n"
"                                        background-color: #252526;\n"
"                                        border: 1px solid #3c3c3c;\n"
"                                        border-radius: 6px;\n"
"                                        padding: 2px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 14px;\n"
"                                    }\n"
"                                    QLineEdit:focus {\n"
"                                        border: 1px solid #007acc;\n"
"                                    }")
        self.lineditARS.setObjectName("lineditARS")

        self.retranslateUi(dialogIngresarARS)
        self.buttonBox.accepted.connect(dialogIngresarARS.accept) # type: ignore
        self.buttonBox.rejected.connect(dialogIngresarARS.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialogIngresarARS)

    def retranslateUi(self, dialogIngresarARS):
        _translate = QtCore.QCoreApplication.translate
        dialogIngresarARS.setWindowTitle(_translate("dialogIngresarARS", "Dialog"))
        self.lblIngresarARS.setText(_translate("dialogIngresarARS", "¿Cuantos pesos argentinos (ARS) ingresas?"))
