# Form implementation generated from reading ui file '.\screens\dialogRegister.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogRegister(object):
    def setupUi(self, dialogRegister):
        dialogRegister.setObjectName("dialogRegister")
        dialogRegister.resize(400, 300)
        dialogRegister.setStyleSheet("dialogRegister {\n"
"    background-color: #1e1e1e;\n"
"}")
        self.btnOkCancelar = QtWidgets.QDialogButtonBox(parent=dialogRegister)
        self.btnOkCancelar.setGeometry(QtCore.QRect(50, 250, 341, 32))
        self.btnOkCancelar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnOkCancelar.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnOkCancelar.setObjectName("btnOkCancelar")
        self.lineditUser = QtWidgets.QLineEdit(parent=dialogRegister)
        self.lineditUser.setGeometry(QtCore.QRect(180, 57, 141, 24))
        self.lineditUser.setStyleSheet("                                    QLineEdit {\n"
"                                        background-color: #252526;\n"
"                                        border: 1px solid #3c3c3c;\n"
"                                        border-radius: 6px;\n"
"                                        padding: 2px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 12px;\n"
"                                    }\n"
"                                    QLineEdit:focus {\n"
"                                        border: 1px solid #007acc;\n"
"                                    }")
        self.lineditUser.setObjectName("lineditUser")
        self.lblPass = QtWidgets.QLabel(parent=dialogRegister)
        self.lblPass.setGeometry(QtCore.QRect(90, 93, 78, 17))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        self.lblPass.setFont(font)
        self.lblPass.setStyleSheet("QLabel {\n"
"                                        background-color: #1e1e1e;\n"
"                                        border: 0px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 14px;        \n"
"                                    }")
        self.lblPass.setObjectName("lblPass")
        self.lineditPass = QtWidgets.QLineEdit(parent=dialogRegister)
        self.lineditPass.setGeometry(QtCore.QRect(180, 90, 141, 24))
        self.lineditPass.setStyleSheet("                                    QLineEdit {\n"
"                                        background-color: #252526;\n"
"                                        border: 1px solid #3c3c3c;\n"
"                                        border-radius: 6px;\n"
"                                        padding: 2px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 12px;\n"
"                                    }\n"
"                                    QLineEdit:focus {\n"
"                                        border: 1px solid #007acc;\n"
"                                    }")
        self.lineditPass.setObjectName("lineditPass")
        self.lblUser = QtWidgets.QLabel(parent=dialogRegister)
        self.lblUser.setEnabled(True)
        self.lblUser.setGeometry(QtCore.QRect(105, 60, 52, 17))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        self.lblUser.setFont(font)
        self.lblUser.setStyleSheet("QLabel {\n"
"                                        background-color: #1e1e1e;\n"
"                                        border: 0px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 14px;        \n"
"                                    }")
        self.lblUser.setObjectName("lblUser")
        self.lblPassConfirm = QtWidgets.QLabel(parent=dialogRegister)
        self.lblPassConfirm.setGeometry(QtCore.QRect(17, 123, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        self.lblPassConfirm.setFont(font)
        self.lblPassConfirm.setStyleSheet("QLabel {\n"
"                                        background-color: #1e1e1e;\n"
"                                        border: 0px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 14px;        \n"
"                                    }")
        self.lblPassConfirm.setObjectName("lblPassConfirm")
        self.lineditPassConfirm = QtWidgets.QLineEdit(parent=dialogRegister)
        self.lineditPassConfirm.setGeometry(QtCore.QRect(180, 120, 141, 24))
        self.lineditPassConfirm.setStyleSheet("                                    QLineEdit {\n"
"                                        background-color: #252526;\n"
"                                        border: 1px solid #3c3c3c;\n"
"                                        border-radius: 6px;\n"
"                                        padding: 2px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 12px;\n"
"                                    }\n"
"                                    QLineEdit:focus {\n"
"                                        border: 1px solid #007acc;\n"
"                                    }")
        self.lineditPassConfirm.setObjectName("lineditPassConfirm")

        self.retranslateUi(dialogRegister)
        self.btnOkCancelar.accepted.connect(dialogRegister.accept) # type: ignore
        self.btnOkCancelar.rejected.connect(dialogRegister.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialogRegister)

    def retranslateUi(self, dialogRegister):
        _translate = QtCore.QCoreApplication.translate
        dialogRegister.setWindowTitle(_translate("dialogRegister", "Dialog"))
        self.lblPass.setText(_translate("dialogRegister", "Contraseña"))
        self.lblUser.setText(_translate("dialogRegister", "Usuario"))
        self.lblPassConfirm.setText(_translate("dialogRegister", "Confirmar Contraseña"))
