# Form implementation generated from reading ui file '.\screens\Login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(512, 475)
        LoginWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #1e1e1e;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnRegister = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnRegister.setGeometry(QtCore.QRect(200, 250, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        font.setBold(True)
        self.btnRegister.setFont(font)
        self.btnRegister.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.btnRegister.setStyleSheet("QPushButton {\n"
"                                        background-color: #0e639c;\n"
"                                        border: none;\n"
"                                        border-radius: 6px;\n"
"                                        color: white;\n"
"                                        font-size: 14px;\n"
"                                        padding: 10px;\n"
"                                        font-weight: bold;\n"
"                                    }\n"
"                                    QPushButton:hover {\n"
"                                        background-color: #1177bb;\n"
"                                    }\n"
"                                    QPushButton:pressed {\n"
"                                        background-color: #094771;\n"
"                                    }")
        self.btnRegister.setObjectName("btnRegister")
        self.btnLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(200, 200, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        font.setBold(True)
        self.btnLogin.setFont(font)
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.btnLogin.setStyleSheet("QPushButton {\n"
"                                        background-color: #57B36A;\n"
"                                        border: none;\n"
"                                        border-radius: 6px;\n"
"                                        color: white;\n"
"                                        font-size: 14px;\n"
"                                        padding: 10px;\n"
"                                        font-weight: bold;\n"
"                                    }\n"
"                                    QPushButton:hover {\n"
"                                        background-color: #66D17C;\n"
"                                    }\n"
"                                    QPushButton:pressed {\n"
"                                        background-color: #438A52;\n"
"                                    }")
        self.btnLogin.setObjectName("btnLogin")
        self.lineditUser = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineditUser.setGeometry(QtCore.QRect(210, 112, 141, 24))
        self.lineditUser.setStyleSheet("                                    QLineEdit {\n"
"                                        background-color: #252526;\n"
"                                        border: 1px solid #3c3c3c;\n"
"                                        border-radius: 6px;\n"
"                                        padding: 2px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 12px;\n"
"                                    }\n"
"                                    QLineEdit:focus {\n"
"                                        border: 1px solid #007acc;\n"
"                                    }")
        self.lineditUser.setObjectName("lineditUser")
        self.lineditPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineditPass.setGeometry(QtCore.QRect(210, 145, 141, 24))
        self.lineditPass.setStyleSheet("                                    QLineEdit {\n"
"                                        background-color: #252526;\n"
"                                        border: 1px solid #3c3c3c;\n"
"                                        border-radius: 6px;\n"
"                                        padding: 2px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 12px;\n"
"                                    }\n"
"                                    QLineEdit:focus {\n"
"                                        border: 1px solid #007acc;\n"
"                                    }")
        self.lineditPass.setObjectName("lineditPass")
        self.lblUser = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblUser.setEnabled(True)
        self.lblUser.setGeometry(QtCore.QRect(135, 115, 52, 17))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        self.lblUser.setFont(font)
        self.lblUser.setStyleSheet("QLabel {\n"
"                                        background-color: #1e1e1e;\n"
"                                        border: 0px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 14px;        \n"
"                                    }")
        self.lblUser.setObjectName("lblUser")
        self.lblPass = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPass.setGeometry(QtCore.QRect(120, 148, 78, 17))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(-1)
        self.lblPass.setFont(font)
        self.lblPass.setStyleSheet("QLabel {\n"
"                                        background-color: #1e1e1e;\n"
"                                        border: 0px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 14px;        \n"
"                                    }")
        self.lblPass.setObjectName("lblPass")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 22))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Compra y Venta de Monedas [Login]"))
        self.btnRegister.setText(_translate("LoginWindow", "Registrarse"))
        self.btnLogin.setText(_translate("LoginWindow", "Iniciar sesión"))
        self.lblUser.setText(_translate("LoginWindow", "Usuario"))
        self.lblPass.setText(_translate("LoginWindow", "Contraseña"))
