# Form implementation generated from reading ui file '.\screens\Main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 442)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboxMoneda = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboxMoneda.setGeometry(QtCore.QRect(70, 170, 111, 31))
        self.comboxMoneda.setStyleSheet("                                    QComboBox {\n"
"                                        background-color: #252526;\n"
"                                        border: 1px solid #3c3c3c;\n"
"                                        border-radius: 6px;\n"
"                                        padding: 2px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 14px;\n"
"                                    }")
        self.comboxMoneda.setMaxVisibleItems(10000000)
        self.comboxMoneda.setObjectName("comboxMoneda")
        self.lblMoneda = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblMoneda.setGeometry(QtCore.QRect(70, 150, 49, 16))
        self.lblMoneda.setObjectName("lblMoneda")
        self.lineditCantidad = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineditCantidad.setGeometry(QtCore.QRect(70, 230, 111, 31))
        self.lineditCantidad.setStyleSheet("                                    QLineEdit {\n"
"                                        background-color: #252526;\n"
"                                        border: 1px solid #3c3c3c;\n"
"                                        border-radius: 6px;\n"
"                                        padding: 2px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 14px;\n"
"                                    }\n"
"                                    QLineEdit:focus {\n"
"                                        border: 1px solid #007acc;\n"
"                                    }")
        self.lineditCantidad.setObjectName("lineditCantidad")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 210, 81, 16))
        self.label.setObjectName("label")
        self.listviewMonedas = QtWidgets.QListView(parent=self.centralwidget)
        self.listviewMonedas.setGeometry(QtCore.QRect(350, 71, 256, 281))
        self.listviewMonedas.setObjectName("listviewMonedas")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(220, 70, 107, 72))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnIngresarARS = QtWidgets.QPushButton(parent=self.widget)
        self.btnIngresarARS.setStyleSheet("QPushButton {\n"
"    background-color: #1976D2;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1565C0;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #0D47A1;\n"
"}")
        self.btnIngresarARS.setObjectName("btnIngresarARS")
        self.verticalLayout.addWidget(self.btnIngresarARS)
        self.btnCrearCuenta = QtWidgets.QPushButton(parent=self.widget)
        self.btnCrearCuenta.setStyleSheet("QPushButton {\n"
"    background-color: #19D2B0;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7AE6D0;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #31917F;\n"
"}")
        self.btnCrearCuenta.setObjectName("btnCrearCuenta")
        self.verticalLayout.addWidget(self.btnCrearCuenta)
        self.btnComprar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnComprar.setGeometry(QtCore.QRect(221, 182, 105, 32))
        self.btnComprar.setStyleSheet("QPushButton {\n"
"    background-color: #19D257;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #5DDE89;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #41965D;\n"
"}")
        self.btnComprar.setObjectName("btnComprar")
        self.btnVender = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnVender.setGeometry(QtCore.QRect(221, 220, 105, 32))
        self.btnVender.setStyleSheet("QPushButton {\n"
"    background-color: #D2BC19;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #D6C660;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #8A7E41;\n"
"}")
        self.btnVender.setObjectName("btnVender")
        self.widget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(70, 270, 185, 40))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 22))
        self.menubar.setObjectName("menubar")
        self.menuCuenta = QtWidgets.QMenu(parent=self.menubar)
        self.menuCuenta.setObjectName("menuCuenta")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setToolTip("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCerrar_sesion = QtGui.QAction(parent=MainWindow)
        self.actionCerrar_sesion.setObjectName("actionCerrar_sesion")
        self.menuCuenta.addAction(self.actionCerrar_sesion)
        self.menubar.addAction(self.menuCuenta.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblMoneda.setText(_translate("MainWindow", "Moneda"))
        self.label.setText(_translate("MainWindow", "Cantidad"))
        self.btnIngresarARS.setText(_translate("MainWindow", "Ingresar ARS"))
        self.btnCrearCuenta.setText(_translate("MainWindow", "Crear Cuenta"))
        self.btnComprar.setText(_translate("MainWindow", "Comprar"))
        self.btnVender.setText(_translate("MainWindow", "Vender"))
        self.label_2.setText(_translate("MainWindow", "ARS para Compra"))
        self.label_3.setText(_translate("MainWindow", "Moneda de preferencia para venta"))
        self.menuCuenta.setTitle(_translate("MainWindow", "Cuenta"))
        self.actionCerrar_sesion.setText(_translate("MainWindow", "Cerrar sesion"))
