# Form implementation generated from reading ui file '.\presentation\screens\Main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 475)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #1e1e1e;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnRegister = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnRegister.setGeometry(QtCore.QRect(126, 210, 101, 41))
        self.btnRegister.setStyleSheet("QPushButton {\n"
"                                        background-color: #0e639c;\n"
"                                        border: none;\n"
"                                        border-radius: 6px;\n"
"                                        color: white;\n"
"                                        font-size: 14px;\n"
"                                        padding: 10px;\n"
"                                        font-weight: bold;\n"
"                                    }\n"
"                                    QPushButton:hover {\n"
"                                        background-color: #1177bb;\n"
"                                    }\n"
"                                    QPushButton:pressed {\n"
"                                        background-color: #094771;\n"
"                                    }")
        self.btnRegister.setObjectName("btnRegister")
        self.btnLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(266, 210, 111, 41))
        self.btnLogin.setStyleSheet("QPushButton {\n"
"                                        background-color: #0e639c;\n"
"                                        border: none;\n"
"                                        border-radius: 6px;\n"
"                                        color: white;\n"
"                                        font-size: 14px;\n"
"                                        padding: 10px;\n"
"                                        font-weight: bold;\n"
"                                    }\n"
"                                    QPushButton:hover {\n"
"                                        background-color: #1177bb;\n"
"                                    }\n"
"                                    QPushButton:pressed {\n"
"                                        background-color: #094771;\n"
"                                    }")
        self.btnLogin.setObjectName("btnLogin")
        self.lineditUser = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineditUser.setGeometry(QtCore.QRect(210, 112, 141, 24))
        self.lineditUser.setStyleSheet("                                    QLineEdit {\n"
"                                        background-color: #252526;\n"
"                                        border: 1px solid #3c3c3c;\n"
"                                        border-radius: 6px;\n"
"                                        padding: 2px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 12px;\n"
"                                    }\n"
"                                    QLineEdit:focus {\n"
"                                        border: 1px solid #007acc;\n"
"                                    }")
        self.lineditUser.setObjectName("lineditUser")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 145, 141, 24))
        self.lineEdit_2.setStyleSheet("                                    QLineEdit {\n"
"                                        background-color: #252526;\n"
"                                        border: 1px solid #3c3c3c;\n"
"                                        border-radius: 6px;\n"
"                                        padding: 2px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 12px;\n"
"                                    }\n"
"                                    QLineEdit:focus {\n"
"                                        border: 1px solid #007acc;\n"
"                                    }")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(134, 110, 72, 61))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblUser = QtWidgets.QLabel(parent=self.widget)
        self.lblUser.setStyleSheet("QLabel {\n"
"                                        background-color: #1e1e1e;\n"
"                                        border: 0px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 14px;        \n"
"                                    }")
        self.lblUser.setObjectName("lblUser")
        self.verticalLayout.addWidget(self.lblUser)
        self.lblPass = QtWidgets.QLabel(parent=self.widget)
        self.lblPass.setStyleSheet("QLabel {\n"
"                                        background-color: #1e1e1e;\n"
"                                        border: 0px;\n"
"                                        color: #d4d4d4;\n"
"                                        font-size: 14px;        \n"
"                                    }")
        self.lblPass.setObjectName("lblPass")
        self.verticalLayout.addWidget(self.lblPass)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnRegister.setText(_translate("MainWindow", "Registrarse"))
        self.btnLogin.setText(_translate("MainWindow", "Iniciar sesión"))
        self.lblUser.setText(_translate("MainWindow", "Usuario"))
        self.lblPass.setText(_translate("MainWindow", "Contraseña"))
